@host = http://localhost:5164

GET {{host}}/tasks
Accept: application/json

###

GET {{host}}/diagnostics/failure
Accept: application/problem+json

###

GET {{host}}/tasks?completed=false
Accept: application/json

###

GET {{host}}/tasks/1
Accept: application/json

###

POST {{host}}/tasks
Content-Type: application/json

{
  "title": "モデルbindingを確認する"
}

###

POST {{host}}/tasks
Content-Type: application/json

{
  "title": "   "
}

###

GET {{host}}/tasks
Accept: application/json
